name: sncf_punctuality
version: "1.0.0"
profile: sncf_punctuality

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  sncf_punctuality:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: external
      +schema: marts
      +format: parquet

seeds:
  sncf_punctuality:
    +schema: seeds
